name: poli__protein
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - biopython
    - python-levenshtein
    - numpy
    - pdb-tools
    - "git+https://github.com/MachineLearningLifeScience/poli.git@master"
