# This dockerfile allows us to run the tests in a container
FROM --platform=linux/amd64 continuumio/anaconda3:latest

# Set working directory
WORKDIR /app

# Copying the files from the host to the container
COPY ./src /app/src
COPY ./pyproject.toml /app/
COPY ./setup.cfg /app/
COPY ./requirements.txt /app/
COPY ./requirements-dev.txt /app/
COPY ./tox.ini /app/

# Installing distutils
RUN apt-get update && \
    apt-get install build-essential -y && \
    apt-get install -y python3.9-distutils

# Installing python dependencies
RUN conda --version
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

# Creating the relevant conda environments
# For chem
RUN conda env create --file src/poli/objective_repository/rdkit_qed/environment.yml

# For proteins
RUN conda env create --file src/poli/objective_repository/foldx_stability/environment.yml
RUN conda env create --file src/poli/objective_repository/rasp/environment.yml

# Running the tests
CMD ["tox"]
