name: poli__rasp
channels:
  - omnia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pdbfixer
  - openbabel
  - openmm
  - mpl-scatter-density
  - pip:
    - "git+https://github.com/MachineLearningLifeScience/poli.git@dev"
    - biopython==1.75
    - torch
    - pandas
    - matplotlib
    - pdb-tools
    - ptitprince
    - scikit-learn
    - pyyaml