name: poli__rasp
channels:
  - omnia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pdbfixer==1.9
  - openbabel
  - openmm
  - mpl-scatter-density
  - clang
  - gcc
  - cmake
  - make
  - pip
  - pip:
    - numpy<2
    - "git+https://github.com/MachineLearningLifeScience/poli.git@dev"
    - biopython==1.72
    - torch
    - pandas
    - matplotlib==3.8.1
    - pdb-tools
    - ptitprince
    - scikit-learn
    - pyyaml
    - PyGithub