name: mario_with_java
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - conda-forge::openjdk
  - pip
  - pip:
    - torch
    - numpy
    - click
    - "git+https://github.com/MachineLearningLifeScience/poli.git@master"
