name: poli__protein_cbas
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - biopython
    - python-levenshtein
    - numpy<2
    - pandas
    - "git+https://github.com/MachineLearningLifeScience/poli.git@master"
