name: poli__lambo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - swig=4.1.1
  - boost-cpp=1.82.0
  - pip=23.2.1
  - pdbfixer
  - openbabel
  - openmm
  - pip:
    - numpy<2
    - "git+https://github.com/MachineLearningLifeScience/poli.git@dev"
    - biopython==1.81
    - botorch==0.8.5
    - gpytorch==1.10
    - hydra-core==1.1.0.dev6
    - python-levenshtein==0.12.2
    - pymoo==0.6.0.1
    - torch==2.0.1
    - pandas==2.0.3
    - cachetools==5.3.1
    - rdkit
    - selfies
    - pytdc
    - pyscreener
    - colorama
    - configparse
    - h5py
    - tqdm
    - scikit-learn
    - "git+https://github.com/samuelstanton/lambo.git@431b052ad0e54a1ba4519272725310127c6377f1"