name: Test (master, conda, python 3.9)

on:
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install tox
    - name: Test linting with tox
      run: |
        tox -c tox.master.ini -e lint
    - name: Test poli-base with tox
      run: |
        tox -c tox.master.ini -e poli-base-py39
    - name: Test poli-chem with tox
      run: |
        tox -c tox.master.ini -e poli-chem-py39
    - name: Test poli-protein with tox
      run: |
        tox -c tox.master.ini -e poli-protein-py39
